.TH DEVFETCH 1 "Setembro 2025" "Devfetch 0.1" "Manual do Usuário"
.SH NOME
devfetch \- mostra informações do ambiente de desenvolvimento (Git, Docker e linguagens)
.SH SINOPSE
.B devfetch
[\fI--git\fR] [\fI--docker\fR] [\fI--dev\fR] [\fI--all\fR]
.SH DESCRIÇÃO
O programa \fBdevfetch\fR é inspirado no neofetch, mas voltado para desenvolvedores.
Ele exibe informações sobre linguagens instaladas, serviços em execução, status do Git e containers do Docker.
